version: "3.5"
services:
  postgres:
    image: postgres:13.2
    ports:
    - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
    - ./src/database:/docker-entrypoint-initdb.d/
  mongo:
    image: mongo
    ports:
    - $MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD