version: "3.5"
services:
  message-broker:
    image: rabbitmq:3.9-management
    hostname: rabbit-broker
    ports:
    - $MESSAGE_BROKER_PORT:5672
    - $MESSAGE_BROKER_ADMIN_PORT:15672
    volumes:
      - ./docker/rabbit-mq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker/rabbit-mq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
  postgres:
    image: postgres
    ports:
    - $DATABASE_PORT:5432
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
    - ./src/database:/docker-entrypoint-initdb.d/
  mongo:
    image: mongo
    ports:
    - $MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE